### ISSUE TITLE
help running

### ISSUE THREAD

**Issue by edentsubery** [lck1201/win_det_heatmaps#13]
Hi, I am not really sure how I should run your project. I tried downloading the resnet file but I am unable to extract it, and not really sure how to use it. Could I have a more detailed explenation of how to train with the resnet option? how should I treat the downloaded file and which are the paths that I need to specify when I try to run it?
Thank you for this great project

**Comment by lck1201** [comment]
hi, the model, xxx.pth.tar is not a zip file. You can just use it directly.
