### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by Yamomoo** [lck1201/win_det_heatmaps#14]
Hi I'm getting the error:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 13.61 GiB (GPU 0; 10.76 GiB total capacity; 4.73 Gib already allocated; 4.09 GiB free; 5.12 GiB reserved in total by PyTorch) If reserved memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Batch Size 4 and 2080Ti

**Comment by lck1201** [comment]
hi, try smaller image size and batch size
