### ISSUE TITLE
AssertionError: (0, IndexError('too many indices for array: array is 1-dimensional, but 2 were indexed'), '0914D92ED9B1A4ECD498DD1E89BA43B1(1).jpg')

### ISSUE THREAD

**Issue by hzxwonder** [lck1201/win_det_heatmaps#5]
Hello, your work is great! It helps me a lot!
But when I run
 ` python infer.py --cfg experiments/resnet/lr1e-3_x120-90-110_center_b2.yaml --model model/resnet18_model_latest.pth.tar --infer ./image `
 It raise an Error like that 
`AssertionError: (0, IndexError('too many indices for array: array is 1-dimensional, but 2 were indexed'), '0914D92ED9B1A4ECD498DD1E89BA43B1(1).jpg')`
 which happens in "\win_det_heatmaps\common_pytorch\net_modules.py" file of line 215.
By the way ,0914D92ED9B1A4ECD498DD1E89BA43B1(1).jpg is contained in the "image" directory.
Thanks a lot!

**Comment by lck1201** [comment]
Could you post the image?
It seems like no valid corner-point detected in this image.

**Comment by hzxwonder** [comment]
![000000000003](https://user-images.githubusercontent.com/52537483/145164061-879aeee6-f75f-4da9-ab22-6e14f9764540.jpg)
just like this.By the way, can this project detect windows inside the house?

**Comment by lck1201** [comment]
The picture is not the "standard facade" supposed to be predicted. It should be like those in provided dataset.

> can this project detect windows inside the house?

I don't know.

**Comment by hzxwonder** [comment]
Ok, thank you for your reply!
